# permissions for end users to edit openstackbaremetalsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: baremetalset-editor-role
rules:
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - openstackbaremetalsets/status
  verbs:
  - get
