
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hco.kubevirt.io
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - metal3.io
  resources:
  - baremetalhosts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - baremetalsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - baremetalsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controlplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - osp-director.openstack.org
  resources:
  - controlplanes/status
  verbs:
  - get
  - patch
  - update
