## Append samples you want in your CSV to this file as resources ##
resources:
- osp-director_v1beta1_controlplane.yaml
- osp-director_v1beta1_vmset.yaml
- osp-director_v1beta1_provisionserver.yaml
- osp-director_v1beta1_openstackbaremetalset.yaml
- osp-director_v1beta1_openstackclient.yaml
- osp-director_v1beta1_overcloudnet.yaml
- osp-director_v1beta1_overcloudipset.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
