apiVersion: osp-director.openstack.org/v1beta1
kind: OvercloudNet
metadata:
  name: ctlplane
spec:
  cidr: 192.168.25.0/24
  allocationStart: 192.168.25.100
  allocationEnd: 192.168.25.250
  gateway: 192.168.25.1 #optional
