apiVersion: osp-director.openstack.org/v1beta1
kind: OpenStackBaremetalSet
metadata:
  name: baremetalset-sample
  namespace: openstack
spec:
  # How many nodes to provision
  replicas: 1
  # The image to install on the provisioned nodes
  rhelImageUrl: http://172.22.0.1/images/rhel-guest-image-8.3-417.x86_64.qcow2.gz
  # The secret containing the SSH pub key to place on the provisioned nodes
  deploymentSSHSecret: osp-baremetalset-ssh-keys
  # Networks to associate with this host
  networks:
    - ctlplane
    - tenant
  role: Compute
  # PasswordSecret the name of the secret used to optionally set the root pwd by adding
  # NodeRootPassword: <base64 enc pwd>
  # to the secret data
  passwordSecret: userpassword
  # The interface on the nodes that will be assigned an IP from the ctlCidr
  ctlplaneInterface: eth2
  # Arbitrary label selector for BaremetalHosts (optional)
  bmhLabelSelector:
    arbitraryKey: arbitraryValue
  # Hardware specs required for the BaremetalHost replicas in this BaremetalSet (optional)
  hardwareReqs:
    cpuReqs:
      # x86_64 or ppc64le (optional)
      arch: x86_64
      # How many cores the CPU should have (optional)
      countReq:
        count: 4
        exactMatch: true
      # Clock speed the CPU should have (optional)
      mhzReq:
        mhz: 2000
        exactMatch: false
    memReqs:
      # Memory the machine should have (optional)
      gbReq:
        gb: 28
        exactMatch: false
    diskReqs:
      # Disk size the machine should have (any disk, optional)
      gbReq:
        gb: 30
        exactMatch: false
      # Should the disk be SSD or rotational (any disk, optional)?
      ssdReq:
        ssd: false
        exactMatch: false
