apiVersion: osp-director.openstack.org/v1beta1
kind: ControlPlane
metadata:
  name: overcloud
  namespace: openstack
spec:
  openStackClientImageURL: quay.io/openstack-k8s-operators/tripleo-deploy:cloud-admin
  passwordSecret: userpassword
  controller:
    role: Controller
    controllerCount: 1
    cores: 6
    memory: 12
    diskSize: 40
    baseImageURL: http://download.eng.brq.redhat.com/brewroot/packages/rhel-guest-image/8.3/417/images/rhel-guest-image-8.3-417.x86_64.qcow2
    storageClass: host-nfs-storageclass
    baseImageVolumeName: openstack-base-img #optional (overrides baseImageURL)
    networks:
      - ctlplane
    ospNetwork:
      bridgeName: br-osp
      name: osp
      desiredState:
        interfaces:
        - name: br-osp # must be same as bridgeName
          description: Linux bridge with enp6s0 as a port
          type: linux-bridge
          state: up
          bridge:
            options:
              stp:
                enabled: false
            port:
            - name: enp6s0
